sudo: false
language: python
python:
  - "2.7"
cache: pip
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r dev-requirements.txt
script:
  - py.test tests/test_tag_release.py
