from .github_actions_modernizer import GithubCIModernizer
from .github_actions_modernizer_django import GithubCIDjangoModernizer
from .setup_file_modernizer import SetupFileModernizer
from .tox_modernizer import ConfigReader, ToxModernizer
from .travis_modernizer import DJANGO_PATTERN, TravisModernizer
