name: Support Windows Issue Creater
on:
  schedule:
    - cron: 0 0 1 */3 *

jobs:
  create_issue:
    name: Create Support Window Issue
    runs-on: ubuntu-20.04
    permissions:
      issues: write
    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "usamasadiq"
          labels: "arbi-bom"
          close-previous: true
          title: "Support Window Update"
          body: |
            ### Description
            Copy the link of the current issue and add it to the [Arbi-bom GitHub Project](https://github.com/orgs/edx/projects/12).

            Follow the steps mentioned in the `repo_tools/barcalendar.py` and check following points for the [Support Window Sheet](https://docs.google.com/spreadsheets/u/2/d/11DheEtMDGrbA9hsUvZ2SEd4Cc8CaC4mAfoV8SVaLBGI/edit#gid=195838733) update.
            For reference, use the respective end of life dates from [endoflife.date](https://endoflife.date/).
            
            - [ ] Update the version of each dependency currently in use, if necessary
            - [ ] Delete any versions older than one prior to the one currently in use
            - [ ] Add end dates which were not previously known
            - [ ] Add new releases that we're likely to consider upgrading to
            - [ ] Do a quick review of our dependencies to see if any categories should be added or removed
          
        env:
          GITHUB_TOKEN: ${{ secrets.requirements_bot_github_token }}
